### ISSUE TITLE
용기친화 식당 정보 추가

### ISSUE THREAD

**Issue by Parkjung1129** [ContainerRestaurant/ContainerRestaurant-Server#109]
피드 정보 또는 식당 정보에 용기 친화 식당여부 정보 추가

용기 친화 식당 여부는 2명이상의 사용자가 용기친화 식당으로(사장님이 환영했어요) 피드 작성이 되었을 때 

True 반환

**Comment by Cenibee** [comment]
용기친화 기능 이후 추천 피드가 사용 불가한 버그가 있어서 이슈를 재오픈 합니다.

### 원인
- `FeedRecommedService` 에서 `FeedPreviewDto` 생성시 `Restaurant` 를 참조하여 용기 친화 정보를 가져오는데, Restaurant 는 지연 로딩 프록시 객체를 갖지만 Feed 는 준영속 객체이기 때문에 에러가 발생함
